version: 2.1

workflows:
  main:
    jobs:
      - build:
          python_version: 3.6
      - build:
          python_version: 3.7

jobs:
  build:
    parameters:
      python_version:
        type: string
    working_directory: ~/circleci-jupytab-python-conda
    docker:
      - image: continuumio/miniconda3
        environment:
          BASH_ENV: ~/.bashrc
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Install conda jupytab environment
          command: |
            conda create -y -n jupytab-conda python=<< parameters.python_version >> make
            conda init bash
      - run:
          name: Install required dependencies and run tests
          no_output_timeout: 3m
          command: |
            conda activate jupytab-conda
            make conda-develop
            make samples-kernel
            make test
      - run:
          name: Static Analysis
          no_output_timeout: 3m
          command: |
            conda activate jupytab-conda
            make flake8
      - store_test_results:
          path: _build/tests
